// Code generated by SQLBoiler 4.3.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bmodels

var TableNames = struct {
	CallbackUrls string
	Merchants    string
	Messages     string
}{
	CallbackUrls: "callback_urls",
	Merchants:    "merchants",
	Messages:     "messages",
}
